export const register = [
    {
        title: "Name",
        value: "",
        cName: "chk-style",
        name: "Name",
        id: localStorage.getItem('id'),
        moreOptions: true,
    },
    {
        title: "LastName",
        value: "",
        cName: "chk-style",
        name: "LastName",
        cType: "text",
        id: "lasName",
    },
    {
        title: "Password",
        value: "",
        cName: "chk-style",
        name: "Password",
        id: "Password",
        cType: "password",
    },
    {
        title: "Confirm Password",
        value: "",
        cName: "chk-style",
        name: "INPEP",
        checked: false,
        id: "confirmPassword",
        cType: "password",
    },
    {
        title: "Phone",
        value: "",
        cName: "chk-style",
        name: "Phone",
        id: "phone",
        cType: "number",
    },
    {
        title: "Email",
        value: "",
        cName: "chk-style",
        name: "email",
        checked: false,
        id: "email",
        cType: "email",
    },
    {
        title: "Discapacidad",
        value: "",
        cName: "chk-style",
        name: "Phone",
        id: "phone",
        cType: "number",
    },
    {
        title: "Register type",
        value: "",
        cName: "chk-style",
        name: "email",
        checked: false,
        id: "email",
        cType: "email",
    },
]